05/26

diff --git a/operate b/operate
--- a/operate
+++ b/operate
@@ -1,5 +1,8 @@
-!/bin/bash
+# #!/bin/bash
 
+SECONDS=0 # Keeping track of the time taken to deploy the solution
+
+# checking arguments
 # Check if the necessary arguments are provided
 if [ $# -lt 3 ]; then
     echo "Error: Please specify the openrc, tag, and ssh_key as ar6guments to install"
@@ -8,164 +11,242 @@ if [ $# -lt 3 ]; then
 fi
 openrc_sr=${1}     # openrc access file
 tag_sr=${2}        # tag for identification of items
-ssh_key_path=${3}  # the ssh_key
+ssh_key_sr=${3}  # the ssh_key
 no_of_servers=$(grep -E '[0-9]' servers.conf) # number of nodes from servers.conf
 
-# Other variables
-natverk_namn="${tag_sr}_network"
-sr_subnet="${tag_sr}_subnet"
-sr_keypair="${tag_sr}_key"
-sr_router="${tag_sr}_router"
-sr_security_group="${tag_sr}_security_group"
-sr_haproxy_server="${tag_sr}_proxy"
-sr_bastion_server="${tag_sr}_bastion"
-sr_server="${tag_sr}_server"
+
+# Define variables
+natverk_namn="${2}_network"
+sr_subnet="${2}_subnet"
+sr_keypair="${2}_key"
+sr_router="${2}_router"
+sr_security_group="${2}_security_group"
+sr_haproxy_server="${2}_proxy"
+sr_bastion_server="${2}_bastion"
+sr_server="${2}_server"
 sshconfig="config"
 knownhosts="known_hosts"
 hostsfile="hosts"
 nodes_yaml="nodes.yaml"
 
-run_status=0 # ansible run status
-
+run_status=0 ##ansible run status
 echo "$(date) Running operate mode for tag: $tag_sr using $openrc_sr for credentials"
 source $openrc_sr
 
-generate_config() {
-    # Extract the second IP address for the bastion server
-    bastionfip=$(openstack server list --name "$sr_bastion_server" -c Networks -f value | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {if (++count == 2) print $1}')
-    
-# Extract the second IP address for the HAProxy server
-    haproxyfip=$(openstack server list --name "$sr_haproxy_server" -c Networks -f value | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {if (++count == 2) print $1}')
-
-    # bastionfip=$(openstack server list --name $sr_bastion_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
-    # haproxyfip=$(openstack server list --name $sr_haproxy_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
-    echo "Bastion IP address: $bastionfip"
-    echo "Proxy IP address: $haproxyfip"
+generate_config(){
+    bastionfip=$(openstack server list --name $sr_bastion_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
+    haproxyfip=$(openstack server list --name $sr_haproxy_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
+       
     echo "$(date) Generating config file"
-    cat <<EOF >> $sshconfig
-Host $sr_bastion_server
-   User ubuntu
-   HostName $bastionfip
-   IdentityFile $ssh_key_sr
-   UserKnownHostsFile /dev/null
-   StrictHostKeyChecking no
-   PasswordAuthentication no
+    echo "Host $sr_bastion_server" >> $sshconfig
+    echo "   User ubuntu" >> $sshconfig
+    echo "   HostName $bastionfip" >> $sshconfig
+    echo "   IdentityFile $ssh_key_sr" >> $sshconfig
+    echo "   UserKnownHostsFile /dev/null" >> $sshconfig
+    echo "   StrictHostKeyChecking no" >> $sshconfig
+    echo "   PasswordAuthentication no" >> $sshconfig
+    echo " " >> $sshconfig
+    echo "Host $sr_haproxy_server" >> $sshconfig
+    echo "   User ubuntu" >> $sshconfig
+    echo "   HostName $haproxyfip" >> $sshconfig
+    echo "   IdentityFile $ssh_key_sr" >> $sshconfig
+    echo "   StrictHostKeyChecking no" >> $sshconfig
+    echo "   PasswordAuthentication no ">> $sshconfig
+    echo "   ProxyJump $sr_bastion_server" >> $sshconfig
 
-Host $sr_haproxy_server
-   User ubuntu
-   HostName $haproxyfip
-   IdentityFile $ssh_key_sr
-   StrictHostKeyChecking no
-   PasswordAuthentication no
-   ProxyJump $sr_bastion_server
-EOF
-
-    # Generate hosts file
-    cat <<EOF > $hostsfile
-[bastion]
-$sr_bastion_server
-
-[proxyserver]
-$sr_haproxy_server
-
-[webservers]
-EOF
-
+    # generate hosts file
+    echo "[bastion]" >> $hostsfile
+    echo "$sr_bastion_server" >> $hostsfile
+    echo " " >> $hostsfile
+    echo "[proxyserver]" >> $hostsfile
+    echo "$sr_haproxy_server" >> $hostsfile   
+    echo " " >> $hostsfile
+    echo "[webservers]" >> $hostsfile
+    
     # The list of running servers
-    active_servers=$(openstack server list --status ACTIVE -f value -c Name | grep -oP "${tag_sr}_server([0-9]+)")
-
-    # Getting IP addresses for servers
+    
+    active_servers=$(openstack server list --status ACTIVE -f value -c Name | grep -oP "${tag_sr}"'_server([0-9]+)')
+    
+    # Getting IP addresses servers
     for server in $active_servers; do
-        ip_address=$(openstack server list --name $server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+')
-        cat <<EOF >> $sshconfig
-
-Host $server
-   User ubuntu
-   HostName $ip_address
-   IdentityFile $ssh_key_sr
-   UserKnownHostsFile /dev/null
-   StrictHostKeyChecking no
-   PasswordAuthentication no
-   ProxyJump $sr_bastion_server
-EOF
-        echo "$server" >> $hostsfile
-        echo "$ip_address" >> $nodes_yaml
+            ip_address=$(openstack server list --name $server -c Networks -f value | grep -Po  '\d+\.\d+\.\d+\.\d+')
+            echo " " >> $sshconfig
+            echo "Host $server" >> $sshconfig
+            echo "   User ubuntu" >> $sshconfig
+            echo "   HostName $ip_address" >> $sshconfig
+            echo "   IdentityFile $ssh_key_sr" >> $sshconfig
+            echo "   UserKnownHostsFile=~/dev/null" >> $sshconfig
+            echo "   StrictHostKeyChecking no" >> $sshconfig
+            echo "   PasswordAuthentication no" >> $sshconfig
+            echo "   ProxyJump $sr_bastion_server" >> $sshconfig 
+            echo "$server" >> $hostsfile
+            echo "$ip_address" >> $nodes_yaml
     done
-
-    cat <<EOF >> $hostsfile
-
-[all:vars]
-ansible_user=ubuntu
-ansible_ssh_private_key_file=$ssh_key_sr
-ansible_ssh_common_args=' -F $sshconfig '
-EOF
+   
+    echo " " >> $hostsfile
+    echo "[all:vars]" >> $hostsfile
+    echo "ansible_user=ubuntu" >> $hostsfile
+    echo "ansible_ssh_private_key_file=$ssh_key_sr" >> $hostsfile
+    echo "ansible_ssh_common_args=' -F $sshconfig '" >> $hostsfile
 }
 
-delete_config() {
-    for file in "$hostsfile" "$sshconfig" "$knownhosts" "$nodes_yaml"; do
-        [[ -f $file ]] && rm $file
+delete_config(){
+
+    for file in "$sshconfig" "$knownhosts" "$hostsfile" "$nodes_yaml"; do
+        if [[ -f "$file" ]]; then
+            rm "$file"
+        fi
     done
 }
 
-while true; do
-    no_of_servers=$(grep -E '[0-9]' servers.conf) # Fetching the number of nodes from servers.conf
+while true
+do
+a=true
+no_of_servers=$(grep -E '[0-9]' servers.conf) # Fetching the number of nodes from servers.conf
+while  [ "$a" = true ]
+do
     echo "$(date) We require $no_of_servers nodes as specified in servers.conf"
 
-    existing_servers=$(openstack server list --status ACTIVE -c Name -f value)
-    devservers_count=$(grep -c $sr_server <<< "$existing_servers")
+    existing_servers=$(openstack server list --status ACTIVE --column Name -f value)
+    #echo "$(date) $existing_servers existing servers."
+    devservers_count=$(grep -c $sr_server <<< $existing_servers)
     echo "$(date) $devservers_count nodes available."
+    
+    total_servers=$(openstack server list --column Name -f value)
+    total_count=$(grep -c $sr_server <<< $total_servers)
 
-    if ((no_of_servers > devservers_count)); then
-        devservers_to_add=$((no_of_servers - devservers_count))
-        echo "$(date) Creating $devservers_to_add more nodes ..."
-        for ((i=0; i<devservers_to_add; i++)); do
-            v=$((RANDOM % 100 + 10))
-            devserver_name="${sr_server}${v}"
-            while openstack server list --status ACTIVE -f value -c Name | grep -qFx "$devserver_name"; do
-                v=$((RANDOM % 100 + 10))
-                devserver_name="${sr_server}${v}"
+
+
+    active_servers=$(openstack server list --status ACTIVE -f value -c Name)
+    count_active_servers=$(grep -oP "${sr_server}" <<< "${active_servers}" | wc -l)
+    # Determine if more servers are needed
+
+    count_active_servers=$(grep -oP "${sr_server}" <<< "${active_servers}" | wc -l)
+
+
+# Determine if more servers are needed
+    if (( no_of_servers > count_active_servers )); then
+        # Calculate the number of servers to add
+        servers_to_add=$((no_of_servers - count_active_servers))
+
+        # Get the list of current active server names
+        current_server_names=$(openstack server list --status ACTIVE -f value -c Name)
+
+        # Get the list of inactive (shutoff) server names
+        inactive_server_names=$(openstack server list --status SHUTOFF -f value -c Name)
+
+        echo "Inactive Nodes: ${inactive_server_names}."
+
+        # Try to start shutoff servers first
+        for server in $inactive_server_names; do
+            if (( servers_to_add <= 0 )); then
+                break
+            fi
+
+            if ! echo "${current_server_names}" | grep -qFx "${server}"; then
+                echo "$(date) Starting inactive server: $server"
+                openstack server start "$server"
+                
+                # Wait for the server to become active
+                while true; do
+                    current_status=$(openstack server show "$server" -f value -c status)
+                    if [[ "$current_status" == "ACTIVE" ]]; then
+                        break
+                    fi
+                    sleep 5 # Add a delay to avoid a tight loop
+                    
+                done
+                run_status=1
+                echo "$(date) Server $server has been started."
+                current_server_names=$(openstack server list --status ACTIVE -f value -c Name)
+                ((servers_to_add--))
+            fi
+        done
+
+        # If still more servers are needed, create new ones
+        while (( servers_to_add > 0 )); do
+            random_suffix=$((RANDOM % no_of_servers + 1))
+            new_server_name="${sr_server}${random_suffix}"
+            
+            used=0
+            until [[ used -eq 1 ]]; do
+                if echo "${current_server_names}" | grep -qFx "${new_server_name}"; then
+                    random_suffix=$((RANDOM % no_of_servers + 1))
+                    new_server_name="${sr_server}${random_suffix}"
+                else
+                    used=1
+                fi
             done
+
+            echo "$(date) Creating ${servers_to_add} additional nodes."
+            echo "New server name: ${new_server_name}"
+            
+            # Create the new server
+            created_node=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" \
+                --key-name "${sr_keypair}" \
+                --flavor "1C-1GB-20GB" \
+                --network "${natverk_namn}" \
+                --security-group "${sr_security_group}" \
+                "${new_server_name}")
+
+            echo "$(date) Node ${new_server_name} created."
             run_status=1
-            openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" "$devserver_name" --key-name "$sr_keypair" --flavor "1C-1GB-20GB" --network "$natverk_namn" --security-group "$sr_security_group"
-            echo "$(date) Created $devserver_name node"
-            while [[ $(openstack server show "$devserver_name" -f value -c status) != "ACTIVE" ]]; do
-                sleep 5
+            ((servers_to_add--))
+            
+            # Wait for the server to become active
+            while true; do
+                current_status=$(openstack server show "${new_server_name}" -f value -c status)
+                if [[ "${current_status}" == "ACTIVE" ]]; then
+                    break
+                fi
+                sleep 5 # Add a delay to avoid a tight loop
+                
             done
+
+            # Update the list of current server names
+            current_server_names=$(openstack server list --status ACTIVE -f value -c Name)
         done
-    elif ((no_of_servers < devservers_count)); then
-        devservers_to_remove=$((devservers_count - no_of_servers))
-        echo "$(date) Removing $devservers_to_remove nodes."
-        run_status=1
-        for ((i=0; i<devservers_to_remove; i++)); do
-            server_to_delete=$(openstack server list --status ACTIVE -f value -c Name | grep -m1 -oP "${tag_sr}_server([0-9]+)")
-            openstack server delete "$server_to_delete" --wait
-            echo "$(date) Removed $server_to_delete node"
+
+    elif (( no_of_servers < count_active_servers )); then
+        # Handle case where there are too many servers
+        echo "$(date) More nodes than required (${no_of_servers}) detected."
+        echo "$(date) Initiating removal of excess nodes."
+        servers_to_remove=$((count_active_servers - no_of_servers))
+        removed_count=0
+
+        while (( removed_count < servers_to_remove )); do
+            server_to_remove=$(openstack server list --status ACTIVE -f value -c Name | grep -m1 -oP "${tag_sr}_server[0-9]+")
+            openstack server delete "${server_to_remove}" --wait
+            echo "$(date) Deleted server ${server_to_remove}."
+            ((removed_count++))
         done
+
     else
-        echo "$(date) Required number of nodes are present."
+        # Handle case where the number of servers is correct
+        echo "$(date) The required number of servers (${no_of_servers}) are already running."
     fi
 
-    current_servers=$(openstack server list --status ACTIVE -c Name -f value)
-    new_count=$(grep -c $sr_server <<< "$current_servers")
-
-    if [[ "$no_of_servers" == "$new_count" && "$run_status" -eq 0 ]]; then
-        echo "$(date) Sleeping 30 seconds. Press CTRL-C if you wish to exit."
+    current_servers=$(openstack server list --status ACTIVE --column Name -f value)
+    new_count=$(grep -c $sr_server <<< $current_servers)
+ 
+    if [[ "$no_of_servers" == "$new_count" &&  "$run_status" -eq 0 ]]
+    then
+        echo "$(date) Sleeping 30 seconds. Press CTRL-C if you wish to exit."    
     else
-        delete_config
-        generate_config
-        echo "$(date) Running ansible-playbook"
-        ansible-playbook -i "$hostsfile" site.yaml
-        run_status=0
-        echo "$(date) Checking node availability through the ${sr_bastion_server}."
-        curl "http://$bastionfip:5000"
-        echo "$(date) Done, the solution has been deployed."
-        echo "$(date) Sleeping 30 seconds. Press CTRL-C if you wish to exit."
-    fi
+            delete_config
+            generate_config
+            echo "$(date) Running ansible-playbook"
+            ansible-playbook -i "$hostsfile" site.yaml
+            sleep 5
+            run_status=0
+            echo "$(date) Checking node availability through the ${sr_bastion_server}."
+            curl http://$bastionfip:5000
+            echo "$(date) Done, the solution has been deployed."
+            echo "$(date) Sleeping 30 seconds. Press CTRL-C if you wish to exit."
 
-    sleep 30
+    fi
+   
+    a=false
 done
-
-
-
-
-
+sleep 30
+done
